config/routes.rb
TuriGuate::Application.routes.draw do
  resources :sites_activities

  resources :sites_services

  resources :branches

  resources :sites

  resources :clicks
  

  resource :advertisements do 
	collection do 
		get 'click'
	end 
  end 
  
  resources :advertisements

  resources :images

  resources :comments

  resources :services

  resources :origins

  resources :events

  resources :locations

  resources :activities
  
  resources :google_map
  
  resources :index do 
	collection do 
		get 'contactUs'
		get 'search'

	end 
  end 
 
	
	      
  devise_for :users
    

root :to => "index#home"

end

app/models/activity.rb
class Activity < ActiveRecord::Base
	validates_presence_of :Description, :message => "- Lo siento, no puedes ingresar una Actividad sin descripcion."
end

app/models/advertisement.rb
class Advertisement < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :image_url, :message => "- Lo siento, no puedes ingresar Publicidad sin direccion de una imagen para mostrar."
  validates_format_of :image_url, :with => %r{\.(gif|jpg|png)$}i, :message => "Ingrese un URL Valido" 
  validates_presence_of :link, :message => "- Lo siento, no puedes ingresar Publicidad sin la direccion externa para mostrar."
end

app/models/branch.rb
class Branch < ActiveRecord::Base
  belongs_to :user
  belongs_to :location
end

app/models/click.rb
class Click < ActiveRecord::Base
  belongs_to :advertisement
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :origin
  
end

app/models/department.rb
class Department < ActiveRecord::Base
	validates_presence_of :Name, :message => "- Lo siento, no puedes ingresar un Departamento sin nombre."
end

app/models/event.rb
class Event < ActiveRecord::Base
	belongs_to :user
	validates_presence_of :description, :message => "- Lo siento, no puedes ingresar un Evento sin descripcion."
	validates_presence_of :title, :message => "- Lo siento, no puedes ingresar un Evento sin título." 
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :origin
end

app/models/location.rb
class Location < ActiveRecord::Base
	validates_presence_of :name, :message => "- Lo siento, no puedes ingresar una Ubicación sin nombre."
end

app/models/origin.rb
class Origin < ActiveRecord::Base
	validates_presence_of :description, :message => "- Lo siento, no puedes ingresar un Origine sin descripción."
end

app/models/service.rb
class Service < ActiveRecord::Base
	validates_presence_of :description, :message => "- Lo siento, no puedes ingresar un Servicio sin descripcion."
end

app/models/site.rb
class Site < ActiveRecord::Base
  belongs_to :user
  belongs_to :location
  
  validates_presence_of :title, :message => "- Lo siento, no puedes ingresar un Sitio sin título."
  validates_presence_of :name, :message => "- Lo siento, no puedes ingresar un Sitio sin nombre."
  validates_presence_of :description, :message => "- Lo siento, no puedes ingresar un Sitio sin descripción."
  validates_presence_of :address, :message => "- Lo siento, no puedes ingresar un Sitio sin dirección."
end

app/models/sites_activity.rb
class SitesActivity < ActiveRecord::Base
  belongs_to :site
  belongs_to :activity
end

app/models/sites_service.rb
class SitesService < ActiveRecord::Base
  belongs_to :site
  belongs_to :service
end

app/models/sites_services.rb
class SitesServices < ActiveRecord::Base
  belongs_to :site
  belongs_to :service
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/branches_controller.rb
class BranchesController < ApplicationController
  # GET /branches
  # GET /branches.xml
  before_filter :authenticate_user!, :except => [:index]
  
  def index
    @branches = Branch.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @branches }
    end
  end

  # GET /branches/1
  # GET /branches/1.xml
  def show
    @branch = Branch.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @branch }
    end
  end

  # GET /branches/new
  # GET /branches/new.xml
  def new
    @branch = Branch.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @branch }
    end
  end

  # GET /branches/1/edit
  def edit
    @branch = Branch.find(params[:id])
  end

  # POST /branches
  # POST /branches.xml
  def create
    @branch = Branch.new(params[:branch])

    respond_to do |format|
      if @branch.save
        format.html { redirect_to(@branch, :notice => 'Branch was successfully created.') }
        format.xml  { render :xml => @branch, :status => :created, :location => @branch }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @branch.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /branches/1
  # PUT /branches/1.xml
  def update
    @branch = Branch.find(params[:id])

    respond_to do |format|
      if @branch.update_attributes(params[:branch])
        format.html { redirect_to(@branch, :notice => 'Branch was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @branch.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /branches/1
  # DELETE /branches/1.xml
  def destroy
    @branch = Branch.find(params[:id])
    @branch.destroy

    respond_to do |format|
      format.html { redirect_to(branches_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/branches_helper.rb
module BranchesHelper
end

app/helpers/clicks_helper.rb
module ClicksHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/origins_helper.rb
module OriginsHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/views/branches/_form.html.erb
<%= form_for(@branch) do |f| %>
  <% if @branch.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@branch.errors.count, "error") %> Error:</h2>

      <ul>
      <% @branch.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user %><br />
    <%= f.text_field :user %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/branches/edit.html.erb
<h1>Editing branch</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @branch %> |
<%= link_to 'Regresar', branches_path %>

app/views/branches/index.html.erb
<h1>Listing branches</h1>

<table>
  <tr>
    <th>Usuario</th>
    <th>Localizacion</th>
    <th>Direccion</th>
    <th>Telefono</th>
    <th>Email</th>
    <th>     </th>
    <th>     </th>
    <th>     </th>
  </tr>

<% @branches.each do |branch| %>
  <tr>
    <td><%= branch.user %></td>
    <td><%= branch.location %></td>
    <td><%= branch.address %></td>
    <td><%= branch.phone %></td>
    <td><%= branch.email %></td>
    <td><%= link_to 'Mostrar', branch %></td>
    <td><%= link_to 'Editar', edit_branch_path(branch) %></td>
    <td><%= Button_to 'Eliminar', branch, :confirm => 'Seguro?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Nuevo', new_branch_path %>

app/views/branches/new.html.erb
<h1>New branch</h1>

<%= render 'form' %>

<%= link_to 'Back', branches_path %>

app/views/branches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @branch.user %>
</p>

<p>
  <b>Location:</b>
  <%= @branch.location %>
</p>

<p>
  <b>Address:</b>
  <%= @branch.address %>
</p>

<p>
  <b>Phone:</b>
  <%= @branch.phone %>
</p>

<p>
  <b>Email:</b>
  <%= @branch.email %>
</p>


<%= link_to 'Edit', edit_branch_path(@branch) %> |
<%= link_to 'Back', branches_path %>