config/routes.rb
TuriGuate::Application.routes.draw do
  resources :sites_activities

  resources :sites_services

  resources :branches

  resources :sites

  resources :clicks
  

  resource :advertisements do 
	collection do 
		get 'click'
	end 
  end 
  
  resources :advertisements

  resources :images

  resources :comments

  resources :services

  resources :origins

  resources :events

  resources :locations

  resources :activities
  
  resources :google_map
  
  resources :index do 
	collection do 
		get 'contactUs'
		get 'search'

	end 
  end 
 
	
	      
  devise_for :users
    

root :to => "index#home"

end

app/models/activity.rb
class Activity < ActiveRecord::Base
	validates_presence_of :Description, :message => "- Lo siento, no puedes ingresar una Actividad sin descripcion."
end

app/models/advertisement.rb
class Advertisement < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :image_url, :message => "- Lo siento, no puedes ingresar Publicidad sin direccion de una imagen para mostrar."
  validates_format_of :image_url, :with => %r{\.(gif|jpg|png)$}i, :message => "Ingrese un URL Valido" 
  validates_presence_of :link, :message => "- Lo siento, no puedes ingresar Publicidad sin la direccion externa para mostrar."
end

app/models/branch.rb
class Branch < ActiveRecord::Base
  belongs_to :user
  belongs_to :location
end

app/models/click.rb
class Click < ActiveRecord::Base
  belongs_to :advertisement
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :origin
  
end

app/models/department.rb
class Department < ActiveRecord::Base
	validates_presence_of :Name, :message => "- Lo siento, no puedes ingresar un Departamento sin nombre."
end

app/models/event.rb
class Event < ActiveRecord::Base
	belongs_to :user
	validates_presence_of :description, :message => "- Lo siento, no puedes ingresar un Evento sin descripcion."
	validates_presence_of :title, :message => "- Lo siento, no puedes ingresar un Evento sin título." 
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :origin
end

app/models/location.rb
class Location < ActiveRecord::Base
	validates_presence_of :name, :message => "- Lo siento, no puedes ingresar una Ubicación sin nombre."
end

app/models/origin.rb
class Origin < ActiveRecord::Base
	validates_presence_of :description, :message => "- Lo siento, no puedes ingresar un Origine sin descripción."
end

app/models/service.rb
class Service < ActiveRecord::Base
	validates_presence_of :description, :message => "- Lo siento, no puedes ingresar un Servicio sin descripcion."
end

app/models/site.rb
class Site < ActiveRecord::Base
  belongs_to :user
  belongs_to :location
  
  validates_presence_of :title, :message => "- Lo siento, no puedes ingresar un Sitio sin título."
  validates_presence_of :name, :message => "- Lo siento, no puedes ingresar un Sitio sin nombre."
  validates_presence_of :description, :message => "- Lo siento, no puedes ingresar un Sitio sin descripción."
  validates_presence_of :address, :message => "- Lo siento, no puedes ingresar un Sitio sin dirección."
end

app/models/sites_activity.rb
class SitesActivity < ActiveRecord::Base
  belongs_to :site
  belongs_to :activity
end

app/models/sites_service.rb
class SitesService < ActiveRecord::Base
  belongs_to :site
  belongs_to :service
end

app/models/sites_services.rb
class SitesServices < ActiveRecord::Base
  belongs_to :site
  belongs_to :service
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  # GET /events
  # GET /events.xml
  
  before_filter :authenticate_user!, :except => [:index, :show] 

      
  def index
    @events = Event.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @events }
    end
  end

  # GET /events/1
  # GET /events/1.xml
  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @event }
    end
  end

  # GET /events/new
  # GET /events/new.xml
  def new
  

    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @event }
    end
  end

  # GET /events/1/edit
  def edit
	@event = Event.find(params[:id])	
	 if @event.user_id != current_user.id 
		redirect_to :back

	 end

  end

  # POST /events
  # POST /events.xml
  def create
    @event = Event.new(params[:event])

    respond_to do |format|
      if @event.save
        format.html { redirect_to(@event, :notice => 'Event was successfully created.') }
        format.xml  { render :xml => @event, :status => :created, :location => @event }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @event.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.xml
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to(@event, :notice => 'Event was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @event.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.xml
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to(events_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/branches_helper.rb
module BranchesHelper
end

app/helpers/clicks_helper.rb
module ClicksHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/origins_helper.rb
module OriginsHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/views/events/_form.html.erb
<%= javascript_include_tag :ckeditor %>				
				<div style="clear: both;">&nbsp;</div>
	
<%= form_for(@event) do |f| %>
 <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %>Error:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :Título %><br />
    <%= f.text_field :title %>
  </div>
  
  <div class="field">
    <%= f.label :descripción %><br />
    <%= f.cktext_area :description, :toolbar=>'Full', :width=>'100%', :height=>'100%' %>	
  </div>
  <div class="field">
    <%= f.label :fecha_inicial %><br />
    <%= f.datetime_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :fecha_final %><br />
    <%= f.datetime_select :final_date %>
  </div>

  <div class="field">
    <%= f.label :link %><br />
    <%= f.text_field :link %>
  </div>  
  
   <div class="field">
    <%= f.label :usuario %><br />
	<%= f.collection_select(:user_id, User.find_by_sql("select * from users where id =" + current_user.id.to_s), :id, :email) %>	
  </div> 
  
  <div class="actions">
    <%= f.submit %>
    <% end %>
  </div>

app/views/events/edit.html.erb
<h1>Editando eventos</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @event %> |
<%= link_to 'Regresar', events_path %>

app/views/events/index.html.erb
<h1>eventos</h1>

<table>
  <tr>
    <th>Titulo</th>  
    <th>Fecha Inicio</th>
    <th>Fecha Fin</th>
    <th>Usuario</th>
    <th>       </th>
    <th>       </th>
    <th>       </th>
  </tr>



<% Event.find_by_sql("SELECT a.*, b.email FROM events a
inner join users b ON a.user_id = b.id" ).each do |event| %>


  <tr>
    <td><%= event.title %></td>  
    <td><%= event.start_date %></td>
    <td><%= event.final_date %></td>
    <td><%= event.email %></td>
    <td><%= link_to 'Mostrar', event %></td>


<% if (defined?(current_user))
   if current_user != nil
   if event.user_id == current_user.id
%>
 
	<td><%= link_to 'Editar', edit_event_path(event) %></td>
	<td><%= button_to 'Borrar', event, :confirm => '¿Esta seguro(a)?', :method => :delete %></td>
<% else %> <td></td>
	<td></td>
<% end end end %>
  </tr>
<% end %>
	
</table>

<br />

<%= link_to 'Nuevo evento', new_event_path %>


<br />

app/views/events/new.html.erb
<h1>Nuevo Evento</h1>

<%= render 'form' %>

<%= link_to 'Regresar', events_path %>

app/views/events/show.html.erb
<%= javascript_include_tag :ckeditor %>	
<p id="notice"><%= notice %></p>


<p>
  <b>Titulo de Evento:</b>
  <%= @event.title %>
</p>

<p>
  <b>Descripcion:</b>
  <%=raw @event.description %>
</p>

<p>
  <b>Fecha Inicio:</b>
  <%= @event.start_date %>
</p>

<p>
  <b>Fecha Fin:</b>
  <%= @event.final_date %>
</p>



<p>
  <b>Link:</b>
  <%= @event.link %>
</p>

<p>
  <b>Usuario:</b>
  <%= @event.user.email %>
</p>


<%= link_to 'Editar', edit_event_path(@event) %> |
<%= link_to 'Regresars', events_path %>


<p>

<table CELLPADDING=2 BORDER=0 WIDTH=620 style="table-layout: fixed; word-wrap: break-word;">
  
<% Comment.find_by_sql("SELECT * FROM comments a
inner join users b ON a.user_id = b.id 
WHERE a.cod_origin_id = 2 AND a.origin_id = " + @event.id.to_s).each do |comment| %>

  <tr>
    <td style="background: #CAE8EA url(images/bg_header.jpg) no-repeat;" ><%= comment.date %></td>
    <td style="background: #CAE8EA url(images/bg_header.jpg) no-repeat;"><%= comment.email %></td>
  </tr>
  <tr>
    <td colspan="2"<i><b><%=raw comment.comment %></i></b></td>	
  </tr>
	<!--	
    <td><%= link_to 'Show', comment %></td>
    <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
    <td><%= link_to 'Destroy', comment, :confirm => 'Are you sure?', :method => :delete %></td>-->
  </tr>
<% end %>
</table>


<p>

<% if (defined?(current_user))
   if current_user != nil
  
%>

<form accept-charset="UTF-8" action="/comments?rediroriginid=<%=@event.id%>&redirorigin=2" class="new_comment" id="new_comment" method="post">
<div style="margin:0;padding:0;display:inline"><input name="utf8" type="hidden" value="&#x2713;" />
<input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>" />
</div>

  <div class="field">
    <label for="comment_date">Date</label><br />
    <select id="comment_date_1i" name="comment[date(1i)]">
<option value="2006">2006</option>
<option value="2007">2007</option>
<option value="2008">2008</option>
<option value="2009">2009</option>
<option value="2010">2010</option>
<option selected="selected" value="2011">2011</option>
<option value="2012">2012</option>
<option value="2013">2013</option>
<option value="2014">2014</option>
<option value="2015">2015</option>
<option value="2016">2016</option>
</select>
<select id="comment_date_2i" name="comment[date(2i)]">
<option value="1">January</option>
<option value="2">February</option>
<option value="3">March</option>
<option value="4">April</option>
<option selected="selected" value="5">May</option>
<option value="6">June</option>
<option value="7">July</option>
<option value="8">August</option>
<option value="9">September</option>
<option value="10">October</option>
<option value="11">November</option>
<option value="12">December</option>
</select>
<select id="comment_date_3i" name="comment[date(3i)]">
<option value="1">1</option>
<option value="2">2</option>
<option value="3">3</option>
<option value="4">4</option>
<option value="5">5</option>
<option value="6">6</option>
<option value="7">7</option>
<option value="8">8</option>
<option value="9">9</option>
<option value="10">10</option>
<option value="11">11</option>
<option value="12">12</option>
<option value="13">13</option>
<option value="14">14</option>
<option value="15">15</option>
<option value="16">16</option>
<option value="17">17</option>
<option value="18">18</option>
<option value="19">19</option>
<option value="20">20</option>
<option value="21">21</option>
<option value="22">22</option>
<option value="23">23</option>
<option value="24">24</option>
<option value="25">25</option>
<option value="26">26</option>
<option value="27">27</option>
<option value="28">28</option>
<option selected="selected" value="29">29</option>
<option value="30">30</option>
<option value="31">31</option>
</select>
 &mdash; <select id="comment_date_4i" name="comment[date(4i)]">
<option selected="selected" value="00">00</option>
<option value="01">01</option>
<option value="02">02</option>
<option value="03">03</option>
<option value="04">04</option>
<option value="05">05</option>
<option value="06">06</option>
<option value="07">07</option>
<option value="08">08</option>
<option value="09">09</option>
<option value="10">10</option>
<option value="11">11</option>
<option value="12">12</option>
<option value="13">13</option>
<option value="14">14</option>
<option value="15">15</option>
<option value="16">16</option>
<option value="17">17</option>
<option value="18">18</option>
<option value="19">19</option>
<option value="20">20</option>
<option value="21">21</option>
<option value="22">22</option>
<option value="23">23</option>
</select>
 : <select id="comment_date_5i" name="comment[date(5i)]">
<option value="00">00</option>
<option value="01">01</option>
<option value="02">02</option>
<option value="03">03</option>
<option value="04">04</option>
<option value="05">05</option>
<option value="06">06</option>
<option value="07">07</option>
<option value="08">08</option>
<option value="09">09</option>
<option value="10">10</option>
<option value="11">11</option>
<option value="12">12</option>
<option value="13">13</option>
<option value="14">14</option>
<option value="15">15</option>
<option value="16">16</option>
<option value="17">17</option>
<option value="18">18</option>
<option value="19">19</option>
<option value="20">20</option>
<option value="21">21</option>
<option value="22">22</option>
<option value="23">23</option>
<option value="24">24</option>
<option value="25">25</option>
<option value="26">26</option>
<option value="27">27</option>
<option value="28">28</option>
<option value="29">29</option>
<option value="30">30</option>
<option value="31">31</option>
<option value="32">32</option>
<option value="33">33</option>
<option selected="selected" value="34">34</option>
<option value="35">35</option>
<option value="36">36</option>
<option value="37">37</option>
<option value="38">38</option>
<option value="39">39</option>
<option value="40">40</option>
<option value="41">41</option>
<option value="42">42</option>
<option value="43">43</option>
<option value="44">44</option>
<option value="45">45</option>
<option value="46">46</option>
<option value="47">47</option>
<option value="48">48</option>
<option value="49">49</option>
<option value="50">50</option>
<option value="51">51</option>
<option value="52">52</option>
<option value="53">53</option>
<option value="54">54</option>
<option value="55">55</option>
<option value="56">56</option>
<option value="57">57</option>
<option value="58">58</option>
<option value="59">59</option>
</select>

  </div>
  
  <div class="field">
    <label for="comment_cod_origin">Cod origin</label><br />
	<select id="comment_cod_origin_id" name="comment[cod_origin_id]">
<option value="2">Evento</option></select>	
  </div> 
  
    
   <div class="field">
    <label for="comment_user">User</label><br />
	<select id="comment_user_id" name="comment[user_id]"><option value="<%= current_user.id %>"><%= current_user.email %></option></select>	
  </div> 
  
  
   <div class="field">
    <label for="comment_origin">Origen:</label><br />
	<select id="comment_origin_id" name="comment[origin_id]"><option value="<%=@event.id%>"><%=@event.description%></option>
</select>	
  </div>   
  


  <div class="field">
    <label for="comment_comment">Comment</label><br />

    <textarea class="editor" cols="70" id="comment_comment_editor" name="comment[comment]" rows="20" style="width:100%;height:100%"></textarea><script type="text/javascript">
//<![CDATA[
if (CKEDITOR.instances['comment_comment_editor']) { 
        CKEDITOR.remove(CKEDITOR.instances['comment_comment_editor']);}
        CKEDITOR.replace('comment_comment_editor', { filebrowserImageBrowseUrl: '/ckeditor/images',height: '100%',toolbar: 'Full',filebrowserImageUploadUrl: '/ckeditor/create/image',language: 'en',filebrowserBrowseUrl: '/ckeditor/files',width: '100%',filebrowserUploadUrl: '/ckeditor/create/file' });
//]]>
</script>

  

  
  <div class="actions">
    <input id="comment_submit" name="commit" type="submit" value="Compartir" />
  </div>
</form>

<%else %>
	PARA AGREGAR COMENTARIOS DEBE INICIAR SESION
<%end  
   else %>
	PARA AGREGAR COMENTARIOS DEBE INICIAR SESION
<%end%>