config/routes.rb
TuriGuate::Application.routes.draw do
  resources :sites_activities

  resources :sites_services

  resources :branches

  resources :sites

  resources :clicks
  

  resource :advertisements do 
	collection do 
		get 'click'
	end 
  end 
  
  resources :advertisements

  resources :images

  resources :comments

  resources :services

  resources :origins

  resources :events

  resources :locations

  resources :activities
  
  resources :google_map
  
  resources :index do 
	collection do 
		get 'contactUs'
		get 'search'

	end 
  end 
 
	
	      
  devise_for :users
    

root :to => "index#home"

end

app/models/activity.rb
class Activity < ActiveRecord::Base
	validates_presence_of :Description, :message => "- Lo siento, no puedes ingresar una Actividad sin descripcion."
end

app/models/advertisement.rb
class Advertisement < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :image_url, :message => "- Lo siento, no puedes ingresar Publicidad sin direccion de una imagen para mostrar."
  validates_format_of :image_url, :with => %r{\.(gif|jpg|png)$}i, :message => "Ingrese un URL Valido" 
  validates_presence_of :link, :message => "- Lo siento, no puedes ingresar Publicidad sin la direccion externa para mostrar."
end

app/models/branch.rb
class Branch < ActiveRecord::Base
  belongs_to :user
  belongs_to :location
end

app/models/click.rb
class Click < ActiveRecord::Base
  belongs_to :advertisement
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :origin
  
end

app/models/department.rb
class Department < ActiveRecord::Base
	validates_presence_of :Name, :message => "- Lo siento, no puedes ingresar un Departamento sin nombre."
end

app/models/event.rb
class Event < ActiveRecord::Base
	belongs_to :user
	validates_presence_of :description, :message => "- Lo siento, no puedes ingresar un Evento sin descripcion."
	validates_presence_of :title, :message => "- Lo siento, no puedes ingresar un Evento sin título." 
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :origin
end

app/models/location.rb
class Location < ActiveRecord::Base
	validates_presence_of :name, :message => "- Lo siento, no puedes ingresar una Ubicación sin nombre."
end

app/models/origin.rb
class Origin < ActiveRecord::Base
	validates_presence_of :description, :message => "- Lo siento, no puedes ingresar un Origine sin descripción."
end

app/models/service.rb
class Service < ActiveRecord::Base
	validates_presence_of :description, :message => "- Lo siento, no puedes ingresar un Servicio sin descripcion."
end

app/models/site.rb
class Site < ActiveRecord::Base
  belongs_to :user
  belongs_to :location
  
  validates_presence_of :title, :message => "- Lo siento, no puedes ingresar un Sitio sin título."
  validates_presence_of :name, :message => "- Lo siento, no puedes ingresar un Sitio sin nombre."
  validates_presence_of :description, :message => "- Lo siento, no puedes ingresar un Sitio sin descripción."
  validates_presence_of :address, :message => "- Lo siento, no puedes ingresar un Sitio sin dirección."
end

app/models/sites_activity.rb
class SitesActivity < ActiveRecord::Base
  belongs_to :site
  belongs_to :activity
end

app/models/sites_service.rb
class SitesService < ActiveRecord::Base
  belongs_to :site
  belongs_to :service
end

app/models/sites_services.rb
class SitesServices < ActiveRecord::Base
  belongs_to :site
  belongs_to :service
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/sites_activities_controller.rb
class SitesActivitiesController < ApplicationController
  # GET /sites_activities
  # GET /sites_activities.xml
   before_filter :authenticate_user!, :except => [:index] 
  def index
    @sites_activities = SitesActivity.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @sites_activities }
    end
  end

  # GET /sites_activities/1
  # GET /sites_activities/1.xml
  def show
    @sites_activity = SitesActivity.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @sites_activity }
    end
  end

  # GET /sites_activities/new
  # GET /sites_activities/new.xml
  def new
    @sites_activity = SitesActivity.new
	
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @sites_activity }
    end
  end

  # GET /sites_activities/1/edit
  def edit
    @sites_activity = SitesActivity.find(params[:id])
  end

  # POST /sites_activities
  # POST /sites_activities.xml
  def create
    @sites_activity = SitesActivity.new(params[:sites_activity])
	@redirsiteid = params[:siteid]
    respond_to do |format|
      if @sites_activity.save
		if @redirsiteid == nil or @redirsiteid.to_s == ""
			format.html { redirect_to(@sites_activity, :notice => 'Sites activity was successfully created.') }
			format.xml  { render :xml => @sites_activity, :status => :created, :location => @sites_activity }
		else
			@site = Site.find_by_id(@redirsiteid)
			format.html { redirect_to(@site, :notice => 'Site Activity was successfully created.' ) }			
		end
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @sites_activity.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /sites_activities/1
  # PUT /sites_activities/1.xml
  def update
    @sites_activity = SitesActivity.find(params[:id])

    respond_to do |format|
      if @sites_activity.update_attributes(params[:sites_activity])
        format.html { redirect_to(@sites_activity, :notice => 'Sites activity was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @sites_activity.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /sites_activities/1
  # DELETE /sites_activities/1.xml
  def destroy
    @sites_activity = SitesActivity.find(params[:id])
    @sites_activity.destroy

    respond_to do |format|
      format.html { redirect_to(sites_activities_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/clicks_helper.rb
module ClicksHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/origins_helper.rb
module OriginsHelper
end

app/helpers/sites_activities_helper.rb
module SitesActivitiesHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/views/sites_activities/_form.html.erb
<%= form_for(@sites_activity) do |f| %>
  <% if @sites_activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sites_activity.errors.count, "error") %> prohibited this sites_activity from being saved:</h2>

      <ul>
      <% @sites_activity.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :site %><br />
	<%= f.collection_select(:site_id, Site.all, :id, :id) %>	
  </div>
  <div class="field">
    <%= f.label :activity %><br />
	<%= f.collection_select(:activity_id, Activity.all, :id, :Description) %>	
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sites_activities/edit.html.erb
<h1>Editing sites_activity</h1>

<%= render 'form' %>

<%= link_to 'Show', @sites_activity %> |
<%= link_to 'Back', sites_activities_path %>

app/views/sites_activities/index.html.erb
<h1>Listing sites_activities</h1>

<table>
  <tr>
    <th>Site</th>
    <th>Activity</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sites_activities.each do |sites_activity| %>
  <tr>
    <td><%= sites_activity.site.name %></td>
    <td><%= sites_activity.activity.Description %></td>
    <td><%= link_to 'Show', sites_activity %></td>
    <td><%= link_to 'Edit', edit_sites_activity_path(sites_activity) %></td>
    <td><%= link_to 'Destroy', sites_activity, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Sites activity', new_sites_activity_path %>

app/views/sites_activities/new.html.erb
<h1>New sites_activity</h1>

<%= render 'form' %>

<%= link_to 'Back', sites_activities_path %>

app/views/sites_activities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Site:</b>
  <%= @sites_activity.site.name %>
</p>

<p>
  <b>Activity:</b>
  <%= @sites_activity.activity.Description %>
</p>


<%= link_to 'Edit', edit_sites_activity_path(@sites_activity) %> |
<%= link_to 'Back', sites_activities_path %>