config/routes.rb
TuriGuate::Application.routes.draw do
  resources :sites_activities

  resources :sites_services

  resources :branches

  resources :sites

  resources :clicks
  

  resource :advertisements do 
	collection do 
		get 'click'
	end 
  end 
  
  resources :advertisements

  resources :images

  resources :comments

  resources :services

  resources :origins

  resources :events

  resources :locations

  resources :activities
  
  resources :google_map
  
  resources :index do 
	collection do 
		get 'contactUs'
		get 'search'

	end 
  end 
 
	
	      
  devise_for :users
    

root :to => "index#home"

end

app/models/activity.rb
class Activity < ActiveRecord::Base
	validates_presence_of :Description, :message => "- Lo siento, no puedes ingresar una Actividad sin descripcion."
end

app/models/advertisement.rb
class Advertisement < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :image_url, :message => "- Lo siento, no puedes ingresar Publicidad sin direccion de una imagen para mostrar."
  validates_format_of :image_url, :with => %r{\.(gif|jpg|png)$}i, :message => "Ingrese un URL Valido" 
  validates_presence_of :link, :message => "- Lo siento, no puedes ingresar Publicidad sin la direccion externa para mostrar."
end

app/models/branch.rb
class Branch < ActiveRecord::Base
  belongs_to :user
  belongs_to :location
end

app/models/click.rb
class Click < ActiveRecord::Base
  belongs_to :advertisement
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :origin
  
end

app/models/department.rb
class Department < ActiveRecord::Base
	validates_presence_of :Name, :message => "- Lo siento, no puedes ingresar un Departamento sin nombre."
end

app/models/event.rb
class Event < ActiveRecord::Base
	belongs_to :user
	validates_presence_of :description, :message => "- Lo siento, no puedes ingresar un Evento sin descripcion."
	validates_presence_of :title, :message => "- Lo siento, no puedes ingresar un Evento sin título." 
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :origin
end

app/models/location.rb
class Location < ActiveRecord::Base
	validates_presence_of :name, :message => "- Lo siento, no puedes ingresar una Ubicación sin nombre."
end

app/models/origin.rb
class Origin < ActiveRecord::Base
	validates_presence_of :description, :message => "- Lo siento, no puedes ingresar un Origine sin descripción."
end

app/models/service.rb
class Service < ActiveRecord::Base
	validates_presence_of :description, :message => "- Lo siento, no puedes ingresar un Servicio sin descripcion."
end

app/models/site.rb
class Site < ActiveRecord::Base
  belongs_to :user
  belongs_to :location
  
  validates_presence_of :title, :message => "- Lo siento, no puedes ingresar un Sitio sin título."
  validates_presence_of :name, :message => "- Lo siento, no puedes ingresar un Sitio sin nombre."
  validates_presence_of :description, :message => "- Lo siento, no puedes ingresar un Sitio sin descripción."
  validates_presence_of :address, :message => "- Lo siento, no puedes ingresar un Sitio sin dirección."
end

app/models/sites_activity.rb
class SitesActivity < ActiveRecord::Base
  belongs_to :site
  belongs_to :activity
end

app/models/sites_service.rb
class SitesService < ActiveRecord::Base
  belongs_to :site
  belongs_to :service
end

app/models/sites_services.rb
class SitesServices < ActiveRecord::Base
  belongs_to :site
  belongs_to :service
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  # GET /activities
  # GET /activities.xml
  
  before_filter :authenticate_user!, :except => [:index]
  

  
  def index
    @activities = Activity.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @activities }
    end
  end

  # GET /activities/1
  # GET /activities/1.xml
  def show
    @activity = Activity.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @activity }
    end
  end

  # GET /activities/new
  # GET /activities/new.xml
  def new
   
   
  
    @activity = Activity.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @activity }
    end
  end

  # GET /activities/1/edit
  def edit
    @activity = Activity.find(params[:id])
  end

  # POST /activities
  # POST /activities.xml
  def create
    @activity = Activity.new(params[:activity])

    respond_to do |format|
      if @activity.save
        format.html { redirect_to(@activity, :notice => 'Activity was successfully created.') }
        format.xml  { render :xml => @activity, :status => :created, :location => @activity }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @activity.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /activities/1
  # PUT /activities/1.xml
  def update
    @activity = Activity.find(params[:id])

    respond_to do |format|
      if @activity.update_attributes(params[:activity])
        format.html { redirect_to(@activity, :notice => 'Activity was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @activity.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.xml
  def destroy
    @activity = Activity.find(params[:id])
    @activity.destroy

    respond_to do |format|
      format.html { redirect_to(activities_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/clicks_helper.rb
module ClicksHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/origins_helper.rb
module OriginsHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/views/activities/_form.html.erb
<%= javascript_include_tag :ckeditor %>
<%= form_for(@activity) do |f| %>
  <% if @activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
      <% @activity.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>

<br />
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Description %><br />
    <%= f.cktext_area :Description, :toolbar=>'Full', :width=>'100%', :height=>'100%' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/activities/edit.html.erb
				
<h1>Editando Actividad</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @activity %> |
<%= link_to 'Regresar', activities_path %>

app/views/activities/index.html.erb
					<p><h3 >Listado de Actividades</h3></p>
<p><h4 align = "center"><%= link_to 'Nueva Actividad', new_activity_path %></h4></p>
</div>

<table border = "1" align = "center">
  <tr>
    <th>Descripción</th>
<% if (defined?(current_user))
   if current_user != nil && current_user.admin
%>	
    <th></th>
    <th></th>
	
<% end end %>	
  </tr>

<% @activities.each do |activity| %>
  <tr>
    <td><%=raw activity.Description %></td>
    <td><%= link_to 'Mostrar', activity %></td>
	
<% if (defined?(current_user))
if current_user != nil && current_user.admin
%>
	
    <td><%= link_to 'Editar', edit_activity_path(activity) %></td>
    <td><%= button_to 'Borrar', activity, :confirm => '¿Estas seguro(a)?', :method => :delete %></td>
<% else %> <td></td>
	<td></td>
<% end end  %>
  </tr>
<% end %></table>

app/views/activities/new.html.erb
<%= render 'form' %>

<%= link_to 'Regresar', activities_path %>

app/views/activities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Descripcion:</b>
  <%=raw @activity.Description %>
  
</p>


<%= link_to 'Editar', edit_activity_path(@activity) %> |
<%= link_to 'Regresar', activities_path %>
<br />